/**
 * The v1 result-code registry is deliberately complete: every uppercase
 * machine code emitted by an engine module must be listed here.  Consumers
 * can therefore branch on a versioned vocabulary instead of parsing causes.
 */
export const RESULT_CODES = Object.freeze([
  'ACCOUNTING_COMPLETE',
  'ASSURANCE_BELOW_FLOOR', 'ASSURANCE_FLOOR_VALID', 'AXES_SCHEMA_INVALID', 'AXES_VALID',
  'ATTESTATION_CODE_INVALID',
  'AUTH_BINDING_MISMATCH', 'AUTH_BINDING_MISSING', 'AUTH_EVENT_SCHEMA_INVALID', 'AUTH_EVENT_TYPE_MISMATCH', 'AUTH_EVENT_VALID', 'AUTH_EXPIRED', 'AUTH_HUMAN_REQUIRED', 'AUTH_MISSING', 'AUTH_POLICY_PROOF_INVALID', 'AUTH_REVOKED', 'AUTH_SUBJECT_MISMATCH', 'AUTH_VALID',
  'BASELINE_GREEN',
  'BENCHMARK_ASSIGNMENT_INVALID', 'BENCHMARK_CRITICAL_SEGMENT_FAILED', 'BENCHMARK_GATE_FAILED', 'BENCHMARK_GRADER_ABSTENTION', 'BENCHMARK_GRADER_ADAPTER_INVALID', 'BENCHMARK_GRADER_ADAPTER_TIMEOUT', 'BENCHMARK_GRADER_COMPLETED', 'BENCHMARK_GRADER_DISAGREEMENT', 'BENCHMARK_GRADER_OUTPUT_EXCEEDED', 'BENCHMARK_INPUT_INVALID', 'BENCHMARK_LINEAGE_INVALID', 'BENCHMARK_MECHANICS_PASS', 'BENCHMARK_PASS', 'BENCHMARK_PROTOCOL_INVALID', 'BENCHMARK_REQUIRED_CATEGORY_MISSING', 'BENCHMARK_REQUIRED_METRIC_MISSING', 'BENCHMARK_RUNNER_INVALID', 'BENCHMARK_RUNNER_OUTPUT_EXCEEDED', 'BENCHMARK_RUNNER_TIMEOUT', 'BENCHMARK_RUN_COMPLETED', 'BENCHMARK_THIN_SEGMENT',
  'CAPABILITY_DOWNGRADE_PREVIEW', 'CAPABILITY_LEGACY_REPORT_ONLY', 'CAPABILITY_MIGRATION_REQUIRED', 'CAPABILITY_OPTIONAL_MISSING', 'CAPABILITY_REQUIRED_MISSING', 'CAPABILITY_SCHEMA_INVALID', 'CAPABILITY_SUPPORTED',
  'DECISIONS_RESOLVED', 'DECISION_AUTHORITY_DOWNGRADE', 'DECISION_CONFLICT', 'DECISION_CYCLE', 'DECISION_MISSING_PREDECESSOR',
  'DELIVERY_EVIDENCE_LEVEL_INSUFFICIENT', 'DELIVERY_EVIDENCE_MISSING', 'DELIVERY_EVIDENCE_STALE', 'DELIVERY_EVIDENCE_WEAK', 'DELIVERY_REWORK_REQUIRED', 'DELIVERY_SCHEMA_INVALID', 'DELIVERY_VALID', 'DELIVERY_VERIFIER_NOT_INDEPENDENT',
  'EVIDENCE_ASSERTIONS_VALID', 'EVIDENCE_ATTESTATION_MISMATCH', 'EVIDENCE_MATCHER_FAILED', 'EVIDENCE_PROCESS_FAILED', 'EVIDENCE_SUBJECT_STALE', 'EVIDENCE_TOOLCHAIN_STALE',
  'ENGINEERING_CHECK_FAILED', 'ENGINEERING_ENVIRONMENT_MISSING', 'ENGINEERING_EVIDENCE_LEVEL_INSUFFICIENT', 'ENGINEERING_EVIDENCE_MISSING', 'ENGINEERING_EVIDENCE_WEAK', 'ENGINEERING_PROFILE_VALID', 'ENGINEERING_SCHEMA_INVALID', 'ENGINEERING_STATUS_INVALID', 'ENGINEERING_VERIFIER_NOT_INDEPENDENT',
  'EXECUTION_AUTHORITY_VALID', 'EXECUTOR_ATTESTATION_MISSING', 'EXECUTOR_FIT', 'EXECUTOR_UNFIT',
  'GATEWAY_DISPATCHED', 'GATEWAY_DISPATCH_FAILED', 'GATEWAY_DISPATCH_UNAVAILABLE', 'GATEWAY_TARGET_DENIED',
  'GATE_EFFECTIVENESS_DECISION_MISMATCH', 'GATE_EFFECTIVENESS_SCHEMA_INVALID', 'GATE_EFFECTIVENESS_VALID',
  'HARD_STOPS_VALID', 'HARD_STOP_FAILED', 'HARD_STOP_UNKNOWN',
  'IMPLEMENTATION_REVIEW_VALID', 'INPUT_MISSING', 'MINIMAL_CHANGE_VALID',
  'INTAKE_CLARIFICATION_REQUIRED', 'INTAKE_DECISION_MISMATCH', 'INTAKE_SCHEMA_INVALID', 'INTAKE_VALID',
  'INCIDENT_REDACTION_INVALID', 'INCIDENT_REGRESSION_CREATED',
  'LEASE_BINDING_MISMATCH', 'LEASE_EXPIRED', 'LEASE_MISSING', 'LEASE_OPERATION_MISMATCH', 'LEASE_REPLAY', 'LEASE_REVOKED', 'LEASE_UNVERIFIED', 'LEASE_VALID',
  'LIFECYCLE_ATTESTATION_INVALID', 'LIFECYCLE_LEGACY_REPORT_ONLY', 'LIFECYCLE_PREDECESSOR_MISMATCH', 'LIFECYCLE_REPLAY', 'LIFECYCLE_REPLAY_UNVERIFIED', 'LIFECYCLE_ROLE_UNAUTHORIZED', 'LIFECYCLE_SCHEMA_INVALID', 'LIFECYCLE_STATE_ADVANCED', 'LIFECYCLE_SUBJECT_MISMATCH', 'LIFECYCLE_TRANSITION_INVALID',
  'PARSE_BLOCK_NAME', 'PARSE_DUPLICATE_KEY', 'PARSE_FIELD_TYPE', 'PARSE_REQUIRED_FIELD', 'PARSE_VALID',
  'PACK_POLICY_CONFLICT', 'PACK_POLICY_VALID', 'PACK_POLICY_WEAKENING', 'PACK_SCHEMA_INVALID', 'PACK_SCOPE_BROADENING',
  'PILOT_AUTHORITY_ATTESTATION_INVALID', 'PILOT_AUTHORITY_ATTESTATION_REQUIRED', 'PILOT_BENCHMARK_NOT_FIELD', 'PILOT_EVIDENCE_INCOMPLETE', 'PILOT_HUMAN_DECISION_REQUIRED', 'PILOT_PROMOTION_DECISION_VALID', 'PILOT_PROMOTION_SCHEMA_INVALID',
  'OUTCOME_DECISION_MISMATCH', 'OUTCOME_ITERATE', 'OUTCOME_KEEP', 'OUTCOME_RETIRE', 'OUTCOME_ROLLBACK', 'OUTCOME_SCHEMA_INVALID',
  'OBSERVATION_PLAN_INVALID', 'OBSERVATION_PLAN_VALID',
  'PROJECTION_AC_MAP_DRIFT', 'PROJECTION_CONTRACT_INVALID', 'PROJECTION_CONTRACT_STALE', 'PROJECTION_EXECUTION_DRIFT', 'PROJECTION_EXECUTION_EVENT_MISMATCH', 'PROJECTION_EXECUTION_EVENT_VALID', 'PROJECTION_FIELD_TYPE', 'PROJECTION_LANDMARKS_VALID', 'PROJECTION_LANDMARK_AMBIGUOUS', 'PROJECTION_LANDMARK_DRIFT', 'PROJECTION_LANDMARK_EXISTS', 'PROJECTION_LANDMARK_MISSING', 'PROJECTION_LANDMARK_RESOLUTION_FAILED', 'PROJECTION_LANDMARK_RESOLVER_MISSING', 'PROJECTION_NON_AUTHORITATIVE', 'PROJECTION_REQUIRED_FIELD', 'PROJECTION_SCOPE_DRIFT', 'PROJECTION_VALID',
  'PRODUCT_DECISION_MISMATCH', 'PRODUCT_PROCEED', 'PRODUCT_REJECTED', 'PRODUCT_REVISION_REQUIRED', 'PRODUCT_SCHEMA_INVALID',
  'PROVENANCE_EXTERNALLY_ATTESTED', 'READINESS_CONTROL_EVIDENCE_MISSING', 'READINESS_DECISIONS', 'READINESS_EXCEPTION_ACTIVE', 'READINESS_EXCEPTION_EXPIRED', 'READINESS_EXCEPTION_SUBJECT_MISMATCH', 'READINESS_OPERATIONAL_EVIDENCE_MISSING', 'READINESS_SCHEMA_INVALID', 'READINESS_VALID',
  'QA_COVERAGE_GATE_FAILED', 'QA_ORACLE_WEAK', 'QA_PROFILE_VALID', 'QA_REQUIRED_TOOL_UNAVAILABLE', 'QA_SCHEMA_INVALID', 'QA_SEEDED_FAULT_MISSING', 'QA_STATUS_INVALID',
  'RISK_BELOW_FLOOR', 'RISK_FLOOR_VALID', 'RISK_PROMOTED', 'RISK_UNKNOWN',
  'RETIRE_CANONICAL_ONLY', 'RETIRE_DURABLE_OUTCOME_MISSING', 'RETIRE_LIVE_DEPENDENCY', 'RETIRE_READY', 'RETIRE_UNRECOVERABLE',
  'ROLE_ASSIGNMENT_STALE', 'ROLE_ATTESTATION_INSUFFICIENT', 'ROLE_AUTHORITY_DEGRADED', 'ROLE_AUTHORITY_MISSING', 'ROLE_AUTHORITY_VALID', 'ROLE_CONFLICT', 'ROLE_SCHEMA_INVALID', 'ROLE_SELF_APPROVAL', 'ROLE_SUBJECT_MISMATCH',
  'REVIEW_MISSING', 'REVIEW_NOT_INDEPENDENT', 'REVIEW_VALID',
  'RELEASE_AUTHORIZATION_INVALID', 'RELEASE_AUTHORIZATION_REPLAY', 'RELEASE_AUTHORIZATION_VALID', 'RELEASE_BINDING_MISMATCH', 'RELEASE_REPLAY_UNVERIFIED',
  'SCOPE_CONFORMANT', 'SCOPE_INCOMPLETE', 'SCOPE_OUT_OF_BOUNDS', 'SCOPE_PATH_ESCAPE', 'SCOPE_SUBJECT_MISMATCH',
  'SIGNATURE_INVALID', 'SUBJECT_NO_GIT', 'SUBJECT_TRUSTED', 'VERSION_SUPPORTED', 'VERSION_UNSUPPORTED',
]);

const CODE_SET = new Set(RESULT_CODES);
export function isResultCode(value) { return CODE_SET.has(value); }
export function assertResultCode(value) {
  if (!isResultCode(value)) throw new TypeError(`unregistered quality-contract result code: ${value}`);
  return value;
}
