/**
 * The v1 result-code registry is deliberately complete: every uppercase
 * machine code emitted by an engine module must be listed here.  Consumers
 * can therefore branch on a versioned vocabulary instead of parsing causes.
 */
export const RESULT_CODES = Object.freeze([
  'ACCOUNTING_COMPLETE',
  'ATTESTATION_CODE_INVALID',
  'AUTH_BINDING_MISMATCH', 'AUTH_BINDING_MISSING', 'AUTH_EVENT_SCHEMA_INVALID', 'AUTH_EVENT_TYPE_MISMATCH', 'AUTH_EVENT_VALID', 'AUTH_EXPIRED', 'AUTH_HUMAN_REQUIRED', 'AUTH_MISSING', 'AUTH_POLICY_PROOF_INVALID', 'AUTH_REVOKED', 'AUTH_SUBJECT_MISMATCH', 'AUTH_VALID',
  'BASELINE_GREEN',
  'DECISIONS_RESOLVED', 'DECISION_AUTHORITY_DOWNGRADE', 'DECISION_CONFLICT', 'DECISION_CYCLE', 'DECISION_MISSING_PREDECESSOR',
  'EVIDENCE_ASSERTIONS_VALID', 'EVIDENCE_ATTESTATION_MISMATCH', 'EVIDENCE_MATCHER_FAILED', 'EVIDENCE_PROCESS_FAILED', 'EVIDENCE_SUBJECT_STALE', 'EVIDENCE_TOOLCHAIN_STALE',
  'EXECUTION_AUTHORITY_VALID', 'EXECUTOR_ATTESTATION_MISSING', 'EXECUTOR_FIT', 'EXECUTOR_UNFIT',
  'GATEWAY_DISPATCHED', 'GATEWAY_DISPATCH_FAILED', 'GATEWAY_DISPATCH_UNAVAILABLE', 'GATEWAY_TARGET_DENIED',
  'IMPLEMENTATION_REVIEW_VALID', 'INPUT_MISSING', 'MINIMAL_CHANGE_VALID',
  'LEASE_BINDING_MISMATCH', 'LEASE_EXPIRED', 'LEASE_MISSING', 'LEASE_OPERATION_MISMATCH', 'LEASE_REPLAY', 'LEASE_REVOKED', 'LEASE_UNVERIFIED', 'LEASE_VALID',
  'PARSE_BLOCK_NAME', 'PARSE_DUPLICATE_KEY', 'PARSE_FIELD_TYPE', 'PARSE_REQUIRED_FIELD', 'PARSE_VALID',
  'PROJECTION_AC_MAP_DRIFT', 'PROJECTION_CONTRACT_INVALID', 'PROJECTION_CONTRACT_STALE', 'PROJECTION_EXECUTION_DRIFT', 'PROJECTION_EXECUTION_EVENT_MISMATCH', 'PROJECTION_EXECUTION_EVENT_VALID', 'PROJECTION_FIELD_TYPE', 'PROJECTION_LANDMARKS_VALID', 'PROJECTION_LANDMARK_AMBIGUOUS', 'PROJECTION_LANDMARK_DRIFT', 'PROJECTION_LANDMARK_EXISTS', 'PROJECTION_LANDMARK_MISSING', 'PROJECTION_LANDMARK_RESOLUTION_FAILED', 'PROJECTION_LANDMARK_RESOLVER_MISSING', 'PROJECTION_NON_AUTHORITATIVE', 'PROJECTION_REQUIRED_FIELD', 'PROJECTION_SCOPE_DRIFT', 'PROJECTION_VALID',
  'PROVENANCE_EXTERNALLY_ATTESTED', 'READINESS_DECISIONS', 'READINESS_VALID',
  'RETIRE_CANONICAL_ONLY', 'RETIRE_DURABLE_OUTCOME_MISSING', 'RETIRE_LIVE_DEPENDENCY', 'RETIRE_READY', 'RETIRE_UNRECOVERABLE',
  'REVIEW_MISSING', 'REVIEW_NOT_INDEPENDENT', 'REVIEW_VALID',
  'SCOPE_CONFORMANT', 'SCOPE_INCOMPLETE', 'SCOPE_OUT_OF_BOUNDS', 'SCOPE_PATH_ESCAPE', 'SCOPE_SUBJECT_MISMATCH',
  'SIGNATURE_INVALID', 'SUBJECT_NO_GIT', 'SUBJECT_TRUSTED', 'VERSION_SUPPORTED', 'VERSION_UNSUPPORTED',
]);

const CODE_SET = new Set(RESULT_CODES);
export function isResultCode(value) { return CODE_SET.has(value); }
export function assertResultCode(value) {
  if (!isResultCode(value)) throw new TypeError(`unregistered quality-contract result code: ${value}`);
  return value;
}
